config/routes.rb
Rails.application.routes.draw do

 

  resources :access do

    collection do
      get :login
    end
  end  

  resources :professionals do

    member do
      get :delete
    end
  end    

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/professional.rb
class Professional < ActiveRecord::Base

	has_and_belongs_to_many :branches
	has_many :contact_details

	has_many :appointments

	has_and_belongs_to_many :clients
	has_many :employments
	has_many :companies, :through => :employments
	
	has_many :update_deletes

	validates_presence_of :first_name

	scope :sorted_name, lambda { order("professionals.first_name ASC")}
	scope :sorted_lastname, lambda { order("professionals.last_name ASC")}
  	scope :newest_first, lambda { order("professionals.created_at DESC")}
  	scope :search, lambda {|query|
    where(["name LIKE ?", "%#{query}%"])}
	
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController

  layout "professional"

  before_action :set_locale


  def index

    @professionals = Professional.sorted_lastname

  end


  def show

    @professional = Professional.find(params[:id])

  end


  def new

     @professional = Professional.new({:first_name => " "})
     @professional_count = Professional.count + 1

  end

  def create

    #Instantiate the new object using the form parameters
    @professional  = Professional.new(professional_params)
# Save the object
   
    if @professional.save
# If the save succeed, it will redirect some where (this case, index action)
    flash[:notice] = " Professional '#{@professional.first_name}' created successfully!"
    redirect_to(:action => 'index')
    
    else 
# If the save fails, redisplay the form so the user can fix the problem and the submit it
     @professional_count = Professional.count + 1
    render('new')
  end
end 


  def edit

     @professional = Professional.find(params[:id])

  end


  def update

     #Find an existing object using the form parameters
      @professional = Professional.find(params[:id])
     
      # Update the object

     if @professional.update_attributes(professional_params)
      flash[:notice] = " Professional '#{@professional.first_name}'' updated successfully!"
      # If the update succeed, it will redirect some where (this case, index action)
      redirect_to(:action => 'show', :id => @professional.id)
      
      else 
      # If the update fails, redisplay the form so the user can fix the problem and the submit it
       @professional_count = Professional.count + 1
       render('edit')
       end

  end

  def delete

     @professional = Professional.find(params[:id])

  end

  def destroy

  #I Find an existing object using the form parameters
    professional = Professional.find(params[:id]).destroy 
    flash[:notice] = " Professional '#{professional.first_name}' destroyed successfully!"
    redirect_to(:action => 'index')

  end


  private

   def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

  def professional_params
    # same as using "params[:subject]", except that it:
    # - raises an error if :subject is not present
    # - allows listed attributes to be mass-assigned
    params.require(:professional).permit(:id_code, :first_name, :last_name, :dob, :email, :specialty, 
      :pass_active, :acc_active, :pasword_digest, :last_in)
  end


end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<%= error_messages_for(@professional) %> 

<div class="table-responsive">
  <table id="fields_table" class="display responsive" summary="Professional form fields">
    <tbody>			
		 <tr>
	   	   <th><%= f.label(:id_code, t(:id_code)) %></th>
	   	   <td><%= f.text_field(:id_code) %></td>
	 	 </tr>
		 <tr>
	       <th><%= f.label(:first_name, t(:first_name)) %></th>
	       <td><%= f.text_field(:first_name) %></td>
	 	 </tr>			 
 		 <tr>
    	   <th><%= f.label(:last_name, t(:last_name)) %></th>
    	   <td><%= f.text_field(:last_name) %></td>
 		 </tr>
		 <tr>
			<th><%= f.label(:dob, t(:dob)) %></th>
		    <td><%= f.date_select(:dob, {:start_year => 1900, :end_year => Time.now.year}) %></td>
				   <!-- This type of entering the date in this xpecific field isn't right as no professional will be born today and be working already . It needs to be fixed-->
		 </tr>
		 <tr>
		    <th><%= f.label(:email, t(:email)) %></th>
		    <td><%= f.text_field(:email) %></td>
		 </tr>
		 <tr>
		    <th><%= f.label(:specialty, t(:specialty)) %></th>
		    <td><%= f.text_field(:specialty) %></td>
		 </tr> 
	<!-- <tr>
		 	<th><%= f.label(:pass_active, t(:pass_active)) %></th>
			<td><%= f.text_field(:pass_active) %></td>
		 </tr>
		 <tr>
			<th><%= f.label(:acc_active, t(:acc_active)) %></th>
			<td><%= f.text_field(:acc_active) %></td>
		 </tr>
		 <tr>
			<th><%= f.label(:password_digest, t(:password_digest)) %></th>
			<td><%= f.text_field(:password_digest) %></td>
		 </tr>
		 <tr>
			<th> Last in </th>
			<td><%= f.date_select(:dob, {:start_year => 1900, :end_year => Time.now.year}) %></td> This will be done authhomatically with touch, it probably will need to be set at the controller
			 </tr> -->

  </table>

app/views/professionals/delete.html.erb
<%= link_to("<< " + t(:return_to), professionals_path, :class => 'back-link') %>

<div class="professionals delete">
  <h2><%= t(:delete) + " " + t(:professional) %></h2>


		<%= form_for(:professional, :url => professional_path(@professional.id), :html => {:method => :delete}) do |f| %>


				<p> A<p> <%= t(:delete_message) %> </p> </p>
	
	 			<p class="reference-name"><%= @professional.first_name %></p>



			<div class="form-buttons">
				<%= submit_tag(t(:delete) + " " + t(:professional)) %>
			</div>

		<% end %>

</div>

app/views/professionals/edit.html.erb
<!--  The partial form is denoted by the underscore symbol(_) before the name of the form -->

<!-- <% @page_tittle = "Update" %>

<%= link_to('<< All Professionals', professionals_path) %> --><!-- RESTful link -->


<%= link_to("<< " + t(:return_to), professionals_path, :class => 'back-link') %>  <!-- RESTful link and translation -->

<div class="professionals edit">
  <h2><%= t(:update) + " " + t(:professional) %></h2>


	<%= form_for(@professional) do |f| %>

			<%= render(:partial => "form", :locals =>{:f =>f}) %>


			<div class="form-buttons">

		      <%= submit_tag(t(:edit) + " " + t(:professional)) %>

			</div>

	<% end %>

</div>

app/views/professionals/index.html.erb
<% @page_title = t(:professional).pluralize(locale) %>

<div class="professionals index">

  <%= link_to(image_tag('plus_sign.png', :size => '13x13', :alt => '+') + " " +t(:add_new_professional), new_professional_path, :class => 'action new') %>

  <div><%= @professionals.size.to_s + " " + t(:professional).pluralize(@professionals.size, locale) + " " + t(:found) %></div> <!-- Here there is a way to pluralize the Object and to translate the variables -->



	<div class="table-responsive">

	<%= javascript_tag("$('#index_table').DataTable( {responsive: true, fixedHeader: true} );") %>
		
    <table id="index_table" class="display responsive" summary="Professional list">
      <thead class="thead-inverse">
    			<tr>
		      	
        		 <th><%= t(:id) %></th>
				 <th><%= t(:id_code) %></th>
				 <th><%= t(:first_name) %></th>
				 <th><%= t(:last_name) %></th>	
				 <th><%= t(:specialty) %></th>
				  <th><%= t(:company).pluralize(locale) %></th>
				 <th><%= t(:branch).pluralize(locale) %></th>
				 <th><%= t(:client).pluralize(locale) %></th>
				 <th><%= t(:appointment).pluralize(locale) %></th>
				 <th><%= t(:action) %></th>
				</tr>
			</thead>
      		<tbody>

				<% @professionals.each do |professional| %>

				<tr class=" cycle('odd', 'even') %">
					<td><%= professional.id %></td>
					<td><%= professional.id_code %></td>
					<td><%= professional.first_name %></td>
					<td><%= professional.last_name %></td>				
					<td><%= professional.specialty %></td>

					<!-- I think I can place above a code that indicates if the professional account is active or not, but I have to search for the way of doing it -->
					<td><%= professional.companies.size %></td>

					<td class="center"><%= professional.branches.size %></td> 
					<td class="center"><%= professional.clients.size %></td> 
					<td class="center"><%= professional.appointments.size %></td> 

					<td class="actions">
						<%= link_to(t(:show), professional_path(professional.id), :class => 'action show') %>
						<%= link_to(t(:edit), edit_professional_path(professional.id), :class => 'action edit') %>
						<%= link_to(t(:delete), delete_professional_path(professional.id), :class => 'action show') %>
						<%= link_to(t(:view_branches), {:controller => 'Branches', :professional_id => professional.id}, :class => 'action show') %>
						<%= link_to(t(:view_clients), {:controller => 'clients', :professional_id => professional.id}, :class => 'action show') %>
						<%= link_to(t(:view_appointments), {:controller => 'appointments', :professional_id => professional.id}, :class => 'action show') %>


						<!-- Here I think that is a great place to place contact details
						<%= link_to(t(:contact_details), {:controller => 'contact_details', :professional_id => professional.id}, :class => 'action show') %> -->


					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>

<%= javascript_tag("$(document).ready( function () {$('#index_table').DataTable();} );") %>


</div>

app/views/professionals/new.html.erb
<!--  The partial form is denoted by the underscore symbol(_) before the name of the form -->


<!-- <%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %> this is the old form of link--> 


<!-- <%= link_to('<< All Professionals', professionals_path) %> <!-- This is the RESTful way of a link -->


<%= link_to("<< " + t(:return_to), professionals_path, :class => 'back-link') %>

<div class="professionals new">
	
	<h2><%= t(:create) + " " + t(:professional) %></h2>


	<%= form_for(@professional) do |f| %>

			<%= render(:partial => "form", :locals =>{:f =>f}) %>	

			<!-- The render above is used to run the new and edit partial form (_form.html.erb) for professionals. -->
			<!-- This is a classic example of Do Not Repeat Yourself -->

			<div class="form_buttons">

		       <%= submit_tag(t(:create) + " " + t(:professional)) %>

			</div>

	<% end %>

</div>

app/views/professionals/show.html.erb
<%= link_to("<< " + t(:return_to), professionals_path, :class => 'back-link') %> 

<div class="professionals show">

	 <h2><%= t(:show) + " " + t(:professional) %></h2> <!-- Translating -->

	 <div class="table-responsive">
    <table id="show_table" class="display responsive" summary="Professional detail view">
      <tbody>

	 <tr>
		<th> <%= t(:id) %></th>	
		<td><%= @professional.id %></td>
	 </tr>
	<th><%= t(:id_code) %></th>
	<td><%= @professional.id_code %></td>
	 </tr>
	 <tr>
		<th><%=  t(:first_name) %></th>
		<td><%= @professional.first_name %></td>
	 </tr>
	 <tr>
		<th><%= t(:last_name) %></th>
		<td><%= @professional.last_name  %></td>
	 </tr>
	 <tr>
		<th><%= t(:d_o_b) %></th>
		<td><%= @professional.dob  %></td>
	 </tr>
	 <tr>
		<th> <%= t(:email) %></th>
		<td><%= @professional.email  %></td>
	 </tr>
	 <tr>
		<th><%= t(:specialty) %></th>
		<td><%= @professional.specialty %></td>
	 </tr>

	 <!-- If Contact Details isn't placed in index  I think that this is a great place to place contact details
	  <%= link_to(t(:contact_details), {:controller => 'contact_details', :professional_id => professional.id}, :class => 'action show') %> -->
	 <tr>
		<th><%= t(:password_active) %></th>
		<td><%= @professional.pass_active ? 'true' : 'false' %></td>
	 </tr>
	 <tr>
		<th><%= t(:account_active) %></th>
		<td><%= @professional.acc_active ? 'true' : 'false' %></td>
	 </tr>
	 <tr>
		<th><%= t(:password_digest) %></th>
		<td><%= @professional.password_digest ? 'true' : 'false' %></td>
	 </tr>
	 <tr>
		<th><%= t(:last_in) %></th>
		<td><%= @professional.last_in %></td>
	 </tr> -->
	 <tr>
		<th><%= t(:Created_at) %></th>
		<td><%= @professional.created_at %></td>
	 </tr>
	 <tr>
		<th> <%= t(:Updated_at) %></th>
		<td><%= @professional.updated_at %></td>
	 </tr>
   	 </table>

</div>